# - import_playbook: ../../docker/install_docker.yml
# - name: Install jobarg_server MySQL
#   hosts: all
#   become: true
#   vars:
#     image_url: "https://www.jobarranger.info/download/6.0.5.1/Docker-image/jobarg-server-mysql-image-6.0.5.1.tar.gz"
#     image_tar: "/tmp/jobarg-server-mysql-image-6.0.5.1.tar.gz"
#   tasks:
#     - name: Download jobarg_server_mysql image
#       ansible.builtin.get_url:
#         url: "{{ image_url }}"
#         dest: "{{ image_tar }}"
#         mode: '0644'
#         force: true

#     - name: Load Docker image from downloaded file
#       community.docker.docker_image:
#         load_path: "{{ image_tar }}"