- name: Manage service
  hosts: all
  become: yes
  tasks:
    - name: Manage service
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: "{{ state }}"
        enabled: "{{ enabled | default(omit) }}"