- name: Install docker on redhats
  hosts: all
  become: true
  tasks:
    - name: Add Docker repo
      ansible.builtin.yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/rhel/$releasever/$basearch/stable
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/rhel/gpg
        file: docker-ce
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["9", "8", "7"]

    - name: Install docker
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
