- name: Install centos 9 stream crb repo
  hosts: all
  become: true
  tasks:
    - name: Install centos 9 stream crb repo
      yum_repository:
        name: centos-stream-9-crb
        description: CentOS Stream 9 CRB Repository
        baseurl: https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/
        gpgcheck: no
        enabled: yes