# add jobarg_agentd on redhat-based servers
- name: Install jobarg_agent (RedHat)
  hosts: redhat_servers
  become: true
  vars:
    rpm_el6: ./el6.rpm # rpm file path
    rpm_el7: ./el7.rpm # rpm file path
    rpm_el8: ./el8.rpm
    rpm_el9: ./el9.rpm

  tasks:
    - name: Copy the RPM file to the remote host redhat9
      ansible.builtin.copy:
        src: "{{ rpm_el9 }}"
        dest: /tmp/jobarg-agent.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["9"]

    - name: Copy the RPM file to the remote host redhat8
      ansible.builtin.copy:
        src: "{{ rpm_el8 }}"
        dest: /tmp/jobarg-agent.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["8"]

    - name: Copy the RPM file to the remote host redhat7
      ansible.builtin.copy:
        src: "{{ rpm_el7 }}"
        dest: /tmp/jobarg-agent.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["7"]

    - name: Copy the RPM file to the remote host redhat6
      ansible.builtin.copy:
        src: "{{ rpm_el6 }}"
        dest: /tmp/jobarg-agent.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["6"]

    - name: Uninstall old jobarranger-agent
      ansible.builtin.yum:
        name:
          - jobarranger-agentd
        state: absent

    - name: Install the RPM package
      ansible.builtin.yum:
        name: /tmp/jobarg-agent.rpm
        state: present
        disable_gpg_check: true
        allow_downgrade: true

# add jobarg_agentd on debian-based servers
- name: Install jobarg_agent (Debian)
  hosts: debian_servers
  become: true
  vars:
    package_src: ./jobarranger-agentd.deb

  tasks:
    - name: Copy the Package file to the remote host debian
      ansible.builtin.copy:
        src: "{{ package_src }}"
        dest: "/tmp/{{ package_src | basename }}"

    - name: Uninstall old jobarranger-agent (Debian)
      apt:
        name:
          - jobarranger-agentd
        purge: true
        state: absent

    - name: Install the jobarg_agent package (Debian)
      apt:
        deb: "/tmp/{{ package_src | basename }}"
        state: present

- name: Managing services for Jobarranger Agent (Debian)
  hosts: debian_servers
  become: true
  tasks:
    - name: Enable jobarg-agentd
      ansible.builtin.service:
        name: jobarg-agentd
        enabled: true

# add jobarg_agentd on amzaon-linux servers
- name: Install jobarg_agent (Amazon_2 & 2023)
  hosts: amazon_linux_servers
  become: true

  tasks:
    - name: Copy the RPM file to the remote host amazon linux 2
      ansible.builtin.copy:
        src: "{{ amzn2 }}"
        dest: /tmp/jobarg-agent.rpm
      when: 
        - ansible_distribution == "Amazon"
        - ansible_distribution_major_version in ["2", "2023"]

    - name: Uninstall old jobarranger-agent
      ansible.builtin.yum:
        name:
          - jobarranger-agentd
        state: absent
      when: 
        - ansible_distribution == "Amazon"
        - ansible_distribution_major_version in ["2", "2023"]
      

    - name: Install the RPM package
      yum:
        name: /tmp/jobarg-agent.rpm
        state: present
        disable_gpg_check: true
        allow_downgrade: true
      when: 
        - ansible_distribution == "Amazon"
        - ansible_distribution_major_version in ["2", "2023"]

- name: Managing services for Jobarranger Agent (Amazon 2 & 2023)
  hosts: amazon_linux_servers
  become: true
  tasks:
    - name: Enable jobarg-agentd
      ansible.builtin.systemd:
        name: jobarg-agentd
        state: started
        enabled: true
      when: 
        - ansible_distribution == "Amazon"
        - ansible_distribution_major_version in ["2", "2023"]