- name: Install epel-release
  import_playbook: ../epel-release/install_epel-release.yml

- name: Install jobarg_server (RedHat)
  hosts: redhat_servers
  become: true
  vars:
    rpm_el7: ./el7.rpm # rpm file path
    rpm_el8: ./el8.rpm
    rpm_el9: ./el9.rpm

  tasks:
    - name: Copy the RPM file to the remote host redhat9
      ansible.builtin.copy:
        src: "{{ rpm_el9 }}"
        dest: /tmp/jobarg-server.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["9"]

    - name: Copy the RPM file to the remote host redhat8
      ansible.builtin.copy:
        src: "{{ rpm_el8 }}"
        dest: /tmp/jobarg-server.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["8"]

    - name: Copy the RPM file to the remote host redhat7
      ansible.builtin.copy:
        src: "{{ rpm_el7 }}"
        dest: /tmp/jobarg-server.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["7"]

    - name: Uninstall old jobarg-server
      ansible.builtin.yum:
        name:
          - jobarranger-server-mysql
          - jobarranger-server-postgresql
        state: absent

    - name: Install the RPM package
      ansible.builtin.yum:
        name: /tmp/jobarg-server.rpm
        state: present
        disable_gpg_check: true
        allow_downgrade: true

# add jobarg_server on debian-based servers
- name: Install jobarg_server (Debian)
  hosts: debian_servers
  become: true
  vars:
    package_src: ./jobarranger-server.deb

  tasks:
    - name: Copy the Package file to the remote host debian
      ansible.builtin.copy:
        src: "{{ package_src }}"
        dest: "/tmp/{{ package_src | basename }}"

    - name: Uninstall old jobarranger-server (Debian)
      apt:
        name:
          - jobarranger-server-postgresql
          - jobarranger-server-mysql
        purge: true
        state: absent

    - name: Install the jobarg_server package (Debian)
      apt:
        deb: "/tmp/{{ package_src | basename }}"
        state: present

- name: Managing services for Jobarranger Server (Debian)
  hosts: debian_servers
  become: true
  tasks:
    - name: Enable jobarg-server
      ansible.builtin.service:
        name: jobarg-server
        enabled: true

# add jobarg_server on amazon-linux servers
- name: Install jobarg_server (Amazon_2)
  hosts: amazon_linux_servers
  become: true

  tasks:
    - name: Copy the RPM file to the remote host amazon linux 2 or 2023
      ansible.builtin.copy:
        src: "{{ amz_2 }}"
        dest: /tmp/jobarg-server.rpm
      when: 
        - ansible_distribution == "Amazon"
        - ansible_distribution_major_version in ["2", "2023"]

    - name: Uninstall old jobarg-server
      ansible.builtin.yum:
        name:
          - jobarranger-server-mysql
          - jobarranger-server-postgresql
        state: absent
      when: 
        - ansible_distribution == "Amazon"
        - ansible_distribution_major_version in ["2", "2023"]

    - name: Install the RPM package
      yum:
        name: /tmp/jobarg-server.rpm
        state: present
        disable_gpg_check: true
        allow_downgrade: true
      when: 
        - ansible_distribution == "Amazon"
        - ansible_distribution_major_version in ["2", "2023"]

- name: Managing services for Jobarranger Agent (Amazon 2 & 2023)
  hosts: amazon_linux_servers
  become: true
  tasks:
    - name: Enable jobarg-server
      ansible.builtin.systemd:
        name: jobarg-server
        state: started
        enabled: true
      when: 
        - ansible_distribution == "Amazon"
        - ansible_distribution_major_version in ["2", "2023"]