- name: Install jobarg_manager
  hosts: all
  become: true
  vars:
    rpm_el8: ./el8.rpm
    rpm_el9: ./el9.rpm

  tasks:
    - name: Copy the RPM file to the remote host redhat9
      ansible.builtin.copy:
        src: "{{ rpm_el9 }}"
        dest: /tmp/jobarg-manager.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["9"]

    - name: Copy the RPM file to the remote host redhat8
      ansible.builtin.copy:
        src: "{{ rpm_el8 }}"
        dest: /tmp/jobarg-manager.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["8"]

    - name: Install the RPM package
      ansible.builtin.yum:
        name: /tmp/jobarg-manager.rpm
        state: present
        disable_gpg_check: true
        allow_downgrade: true