- name: Install php-mysqlnd
  import_playbook: ../php/install_php-mysqlnd.yml

- name: Install php-pgsql
  import_playbook: ../php/install_php-pgsql.yml

- name: Install jobarg_manager (RedHat)
  hosts: redhat_servers
  become: true
  vars:
    rpm_el8: ./el8.rpm
    rpm_el9: ./el9.rpm

  tasks:
    - name: Copy the RPM file to the remote host redhat9
      ansible.builtin.copy:
        src: "{{ rpm_el9 }}"
        dest: /tmp/jobarg-manager.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["9"]

    - name: Copy the RPM file to the remote host redhat8
      ansible.builtin.copy:
        src: "{{ rpm_el8 }}"
        dest: /tmp/jobarg-manager.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["8"]

    - name: Uninstall old jobarranger-manager
      ansible.builtin.yum:
        name:
          - jobarranger-manager
        state: absent

    - name: Install the RPM package
      ansible.builtin.yum:
        name: /tmp/jobarg-manager.rpm
        state: present
        disable_gpg_check: true
        allow_downgrade: true

- name: Managing services for jobarg_manager (RedHat)
  hosts: redhat_servers
  become: true
  tasks:
    - name: Stop and disable firewalld for rhel
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: false

    - name: Restart and enable php-fpm for rhel
      ansible.builtin.service:
        name: php-fpm
        state: restarted
        enabled: true

    - name: Restart and enable httpd for rhel
      ansible.builtin.service:
        name: httpd
        state: restarted
        enabled: true

# add jobarg_manager on debian-based servers
- name: Install jobarg_manager (Debian)
  hosts: debian_servers
  become: true
  vars:
    package_src: ./jobarranger-manager.deb

  tasks:
    - name: Copy the Package file to the remote host debian
      ansible.builtin.copy:
        src: "{{ package_src }}"
        dest: "/tmp/{{ package_src | basename }}"

    - name: Uninstall old jobarranger-manager
      apt:
        name:
          - jobarranger-manager
        purge: true
        state: absent

    - name: Install php-mysqlnd and php-pgsql
      apt:
        name:
          - php-mysqlnd
          - php-pgsql
        state: present

    - name: Install the jobarg_manager package
      apt:
        deb: "/tmp/{{ package_src | basename }}"
        state: present

- name: Managing services for jobarg_manager (Debian)
  hosts: debian_servers
  become: true
  tasks:
    - name: Restart and enable apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
        enabled: true
