- name: Install php-mysqlnd
  import_playbook: ../php/install_php-mysqlnd.yml

- name: Install php-pgsql
  import_playbook: ../php/install_php-pgsql.yml

- name: Install jobarg_manager
  hosts: all
  become: true
  vars:
    rpm_el8: ./el8.rpm
    rpm_el9: ./el9.rpm

  tasks:
    - name: Copy the RPM file to the remote host redhat9
      ansible.builtin.copy:
        src: "{{ rpm_el9 }}"
        dest: /tmp/jobarg-manager.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["9"]

    - name: Copy the RPM file to the remote host redhat8
      ansible.builtin.copy:
        src: "{{ rpm_el8 }}"
        dest: /tmp/jobarg-manager.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["8"]
    
    - name: Uninstall old jobarg-manager
      ansible.builtin.yum:
        name:
          - jobarg-manager
        state: absent

    - name: Install the RPM package
      ansible.builtin.yum:
        name: /tmp/jobarg-manager.rpm
        state: present
        disable_gpg_check: true
        allow_downgrade: true

- name: Stop and disable firewalld for rhel
  import_playbook: ../service/manage_service.yml
  vars:
      service_name: firewalld
      state: stopped
      enabled: no
  when: ansible_os_family == "RedHat"

- name: Restart and enable php-fpm for rhel
  import_playbook: ../service/manage_service.yml
  vars:
      service_name: php-fpm
      state: restarted
      enabled: yes
  when: ansible_os_family == "RedHat"

- name: Restart and enable httpd for rhel
  import_playbook: ../service/manage_service.yml
  vars:
      service_name: httpd
      state: restarted
      enabled: yes
  when: ansible_os_family == "RedHat"