- name: Install php-mysqlnd
  import_playbook: ../php/install_php-mysqlnd.yml

- name: Install php-pgsql
  import_playbook: ../php/install_php-pgsql.yml

- name: Install jobarg_manager (RedHat)
  hosts: redhat_servers
  become: true
  vars:
    rpm_el8: ./el8.rpm
    rpm_el9: ./el9.rpm

  tasks:
    - name: Copy the RPM file to the remote host redhat9
      ansible.builtin.copy:
        src: "{{ rpm_el9 }}"
        dest: /tmp/jobarg-manager.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["9"]

    - name: Copy the RPM file to the remote host redhat8
      ansible.builtin.copy:
        src: "{{ rpm_el8 }}"
        dest: /tmp/jobarg-manager.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["8"]

    - name: Copy the RPM file to the remote host redhat7
      ansible.builtin.copy:
        src: "{{ rpm_el7 }}"
        dest: /tmp/jobarg-manager.rpm
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["7"]

    - name: Uninstall old jobarranger-manager
      ansible.builtin.yum:
        name:
          - jobarranger-manager
        state: absent

    - name: Install the RPM package
      ansible.builtin.yum:
        name: /tmp/jobarg-manager.rpm
        state: present
        disable_gpg_check: true
        allow_downgrade: true

    - name: Create log directory
      ansible.builtin.file:
        path: "/var/log/jobarranger/manager"
        state: directory
        owner: apache
        group: apache
        mode: '0755'

- name: Managing services for jobarg_manager (RedHat)
  hosts: redhat_servers
  become: true
  tasks:
    - name: Stop and disable firewalld for rhel
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: false

    - name: Restart and enable php-fpm for rhel
      ansible.builtin.service:
        name: php-fpm
        state: restarted
        enabled: true

    - name: Restart and enable httpd for rhel
      ansible.builtin.service:
        name: httpd
        state: restarted
        enabled: true

# add jobarg_manager on debian-based servers
- name: Install jobarg_manager (Debian)
  hosts: debian_servers
  become: true
  vars:
    package_src: ./jobarranger-manager.deb

  tasks:
    - name: Copy the Package file to the remote host debian
      ansible.builtin.copy:
        src: "{{ package_src }}"
        dest: "/tmp/{{ package_src | basename }}"

    - name: Uninstall old jobarranger-manager
      apt:
        name:
          - jobarranger-manager
        purge: true
        state: absent

    - name: Install php-mysqlnd and php-pgsql
      apt:
        name:
          - php-mysqlnd
          - php-pgsql
        state: present

    - name: Install the jobarg_manager package
      apt:
        deb: "/tmp/{{ package_src | basename }}"
        state: present

    - name: Create log directory
      ansible.builtin.file:
        path: "/var/log/jobarranger/manager"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

- name: Managing services for jobarg_manager (Debian)
  hosts: debian_servers
  become: true
  tasks:
    - name: Restart and enable apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
        enabled: true

# add jobarg_manager on amazonlinux server
- name: Install jobarg_manager (Amazon_2 & 2023)
  hosts: amazon_linux_servers
  become: true

  tasks:
    - name: Copy the RPM file to the remote host amazon linux 2 or 2023
      ansible.builtin.copy:
        src: "{{ amzn2 }}"
        dest: /tmp/jobarg-manager.rpm
    
    - name: Enable Amazon Extras for PHP 7.2
      ansible.builtin.command: amazon-linux-extras enable php7.2
      when: 
      - ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

    - name: Other required PHP packages on Amazon Linux 2
      ansible.builtin.yum:
        name:
          - httpd
          - php-cli
          - php-common
          - php-fpm
          - php-mbstring
          - php-pdo
          - php-xml
        state: present
      when: 
        - ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

    - name: Install PHP 8.1 for Amazon linux 2023
      ansible.builtin.yum:
        name: php8.1
        state: present
      when:
        - ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"

    - name: Install additional PHP extensions+ for Amazon linux 2 and 2023
      ansible.builtin.yum:
        name:
          - php-mysqlnd
          - php-pgsql
        state: present

    - name: Uninstall old jobarranger-manager
      ansible.builtin.yum:
        name:
          - jobarranger-manager
        state: absent

    - name: Install the RPM package
      yum:
        name: /tmp/jobarg-manager.rpm
        state: present
        disable_gpg_check: true
        allow_downgrade: true

    - name: Create log directory
      ansible.builtin.file:
        path: "/var/log/jobarranger/manager"
        state: directory
        owner: apache
        group: apache
        mode: '0755'

- name: Managing services for jobarg_manager (Amazon linux 2 & 2023)
  hosts: amazon_linux_servers
  become: true
  tasks:
    - name: Stop and disable firewalld for Amazon linux 2
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false
      when: firewalld_status is defined and firewalld_status.rc == 0

    - name: Restart and enable php-fpm for Amazon linux 2
      ansible.builtin.systemd:
        name: php-fpm
        state: restarted
        enabled: true

    - name: Restart and enable httpd for Amazon linux 2
      ansible.builtin.systemd:
        name: httpd
        state: restarted
        enabled: true