- name: Install php-mysqlnd
  hosts: all
  become: true
  tasks:
    - name: Install php-mysqlnd
      ansible.builtin.dnf:
        name: php-mysqlnd 
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version in ["8", "9"]